Added a simple ping counter
XLabsProject/iw6x-client pull request #105
Opened 2020-10-24 15:47 UTC by halcyo-n

Simple ping counter that renders the same way as CG_DrawFPS
I'm sure there are better ways to do it but as commented in the code i don't want to mess things up, this is simply a start but if you're aiming for a early pre release this month i'm sure the playerbase would appreciate a ping counter.

2020-10-25 19:36 UTC, momo5502 requested changes
Please, don't commit submodule changes. Merge the master into your fork if you didn't touch the submodules.
The whole approach is kinda meh, changing the scoreboard would be way better, but I guess it's fine until there is a way to adjust the scoreboard

2020-10-25 19:36 UTC, momo5502 commented on src/client/game/dvars.cpp
> +    game::dvar_t* cg_drawPing = nullptr;
Formatting...

2020-10-25 19:36 UTC, momo5502 commented on src/client/module/fps.cpp
> +		float ping_color[4] = { 1.0f, 1.0f, 1.0f, 0.65f };
Formatting...

2020-10-25 19:36 UTC, momo5502 commented on src/client/module/fps.cpp
> +				uintptr_t ping_offset = 0x1419E5100;
What's the point of saving that value? Just directly do a reinterpret cast

2020-10-25 19:36 UTC, momo5502 commented on src/client/module/fps.cpp
> +				//todo: implement a check if drawFPS is >1, then push ping counter under fps counter
Why are you creating a pull request if your code is unfinished?
Directly place the ping counter at a suited position, don't adapt the behaviour depending on cg_drawfps

2020-10-25 19:36 UTC, momo5502 commented on src/client/module/fps.cpp
> +				//todo: implement this into scoreboard? i don't wanna touch the scoreboard considering the state it's in at the moment.
Yes, this would actually be the only reasonable solution

2020-10-25 19:36 UTC, momo5502 commented on src/client/module/fps.cpp
> +			//utils::hook::call(SELECT_VALUE(0x1419E50FF, 0x1419E5100), &cg_draw_ping_register_stub);
Why?

2020-10-25 19:36 UTC, momo5502 commented on src/client/module/fps.cpp
> +		void cg_draw_ping_register_stub(const char* name, const char** _enum, const int value, unsigned int flags,
Empty line?

2020-10-26 10:47 UTC, halcyo-n commented
Had a hard time working with the formatting changes cus github desktop is stupid, hopefully all is well now

2020-10-26 11:48 UTC, momo5502 approved these changes
cba to wait for you to fix the formatting, I'll fix it myself

2020-10-26 11:48 UTC, momo5502 commented on src/client/game/dvars.cpp
> +    game::dvar_t* cg_drawPing = nullptr;
formatting is still fucked.

2020-10-26 11:48 UTC, momo5502 commented on src/client/module/fps.cpp
> +		float ping_color[4] = { 1.0f, 1.0f, 1.0f, 0.65f };
formatting is still fucked?

2020-10-26 11:48 UTC, merged

2020-10-26 11:50 UTC, halcyo-n commented
Formatting was aligned within VS but github desktop didn't seem to pick up on the changes

2020-10-26 12:32 UTC, momo5502 commented
You also committed a submodule and your dvar registration was completely separate from your usage. 
I created a commit that fixes those things: https://github.com/XLabsProject/iw6x-client/commit/3fc730313e6a4b5acfc7d644ee25f774d633b10a
Next time, please try to fix these things yourself.