Change steam_id generation to a more suitable random
XLabsProject/iw6x-client pull request #178
Opened 2020-11-05 23:15 UTC by skiff

The old steam id generation was not random enough and caused collisions to happen across players. When two players with the same id tried to join a server, there would be a crash rooting in SV_DirectConnect because it thought it needed to reconnect a player that was already in the session state. Temporary fix for now, some method to guarantee no collisions may be needed down the road

2020-11-05 23:18 UTC, momo5502 requested changes

2020-11-05 23:18 UTC, momo5502 commented on src/client/steam/interfaces/user.cpp
> -			id.bits = 0x110000100000000 | (rand() & ~0x80000000);
& ~0x800... is needed. It kills the 32nd bit, as steam ids must only use the last 31 bits

2020-11-06 01:56 UTC, skiff commented on src/client/steam/interfaces/user.cpp
> -			id.bits = 0x110000100000000 | (rand() & ~0x80000000);
made the changes, but the issue still persisted from before after some testing

2020-11-06 14:02 UTC, momo5502 approved these changes

2020-11-06 14:13 UTC, merged