add give command
XLabsProject/iw6x-client pull request #187
Opened 2020-11-07 12:08 UTC by Joelrau

here are some weapons codenames:
defaultweapon_mp
iw6_ak12_mp
iw6_ameli_mp
iw6_arx160_mp
iw6_bren_mp
iw6_cbjms_mp
iw6_fads_mp
iw6_fp6_mp
iw6_g28_mp
iw6_gm6_mp
iw6_gm6helisnipe_mp
iw6_honeybadger_mp
iw6_imbel_mp
iw6_k7_mp
iw6_kac_mp
iw6_knifeonly_mp
iw6_knifeonlyjugg_mp
iw6_kriss_mp
iw6_l115a3_mp
iw6_lsat_mp
iw6_m9a1_mp
iw6_m27_mp
iw6_maaws_mp
iw6_maawschild_mp
iw6_maawshoming_mp
iw6_magnum_mp
iw6_magnumhorde_mp
iw6_magnumjugg_mp
iw6_maul_mp
iw6_microtar_mp
iw6_minigun_mp
iw6_minigunjugg_mp
iw6_mk14_mp
iw6_mk32_mp
iw6_mk32horde_mp
iw6_mp443_mp
iw6_msbs_mp
iw6_mts255_mp
iw6_p226_mp
iw6_p226jugg_mp
iw6_panzerfaust3_mp
iw6_pdw_mp
iw6_pp19_mp
iw6_r5rgp_mp
iw6_rgm_mp
iw6_riotshield_mp
iw6_riotshieldjugg_mp
iw6_sc2010_mp
iw6_svu_mp
iw6_usr_mp
iw6_uts15_mp
iw6_vepr_mp
iw6_vks_mp

2020-11-09 10:43 UTC, momo5502 requested changes

2020-11-09 10:43 UTC, momo5502 commented on src/client/game/game.cpp
> +			G_GivePlayerWeapon = G_GivePlayerWeapon_t(SELECT_VALUE(0, 0x1403DA5E0));
SP support would be nice

2020-11-09 12:33 UTC, Joelrau commented on src/client/game/game.cpp
> +			G_GivePlayerWeapon = G_GivePlayerWeapon_t(SELECT_VALUE(0, 0x1403DA5E0));
👍 doing it

2020-11-09 13:47 UTC, avail commented on src/client/game/structs.hpp
> +	enum errorParm
Parm?

2020-11-09 14:50 UTC, momo5502 requested changes
see comments in the commit

2020-11-09 14:51 UTC, avail commented
> Also, yeah, parm?

actually I think that one is c&p from another place, iirc I saw errorParm in another PR some time ago

2020-11-09 14:52 UTC, momo5502 commented
> > Also, yeah, parm?
> 
> actually I think that one is c&p from another place, iirc I saw errorParm in another PR some time ago

little avail stalking IW6x pull requests :P

2020-11-09 14:58 UTC, avail commented
> > > Also, yeah, parm?
> > 
> > 
> > actually I think that one is c&p from another place, iirc I saw errorParm in another PR some time ago
> 
> little avail stalking IW6x pull requests :P

heh I've watched this even before any code was in it :P

2020-11-09 14:59 UTC, Joelrau commented on src/client/game/structs.hpp
> +	enum errorParm
> Also, yeah, parm?

That's what it's called in iw6_ds.pdb

2020-11-09 14:59 UTC, Joelrau commented
> > Also, yeah, parm?
> 
> actually I think that one is c&p from another place, iirc I saw errorParm in another PR some time ago

yeah was from my fast_restart pr, but closed that one.

2020-11-10 04:00 UTC, momo5502 commented on src/client/game/structs.hpp
> +	enum errorParm
Haha fr? Wtf 😂

2020-11-10 04:00 UTC, momo5502 approved these changes

2020-11-10 04:00 UTC, merged