Add fastfiles module
XLabsProject/iw6x-client pull request #199
Opened 2020-11-12 16:19 UTC by Joelrau

2020-11-12 17:45 UTC, momo5502 requested changes

2020-11-12 17:45 UTC, momo5502 commented on src/client/module/fastfiles.cpp
> +			if (game::environment::is_sp())
Why no sp support?

2020-11-12 18:16 UTC, Joelrau commented on src/client/module/fastfiles.cpp
> +			if (game::environment::is_sp())
Fine, I'll do it.

2020-11-15 22:24 UTC, momo5502 commented
Please update to new symbol and component style and it's fine

2020-11-20 07:31 UTC, momo5502 approved these changes

2020-11-20 07:31 UTC, merged