allow PlayerCmd_SetClientDvar to change any dvar like old cods
XLabsProject/iw6x-client pull request #224
Opened 2020-11-29 19:28 UTC by skiff

This change allows SetClientDvar to change dvars that are not network dvars. On old cods it would send the SV_GameSendServerCommand with the dvar name as a string. On Ghosts, it converts the dvar name to an ID and sends that instead. The ID is only valid for network dvars (replicated & whatever 0x10 is). This will be handy for scripting when people make their own mods and need the ability to change client dvars

2020-11-29 20:50 UTC, momo5502 requested changes

2020-11-29 20:50 UTC, momo5502 commented on src/client/component/dvar_cheats.cpp
> +	void cg_set_client_dvar_from_server(int local_client_num, game::mp::cg_s* cg, const char* dvar_id, const char* value)
local_client_num can be const

2020-11-29 20:50 UTC, momo5502 commented on src/client/component/dvar_cheats.cpp
> +	void set_client_dvar_by_string(int entity_num, const char* value)
entity_num can be const

2020-11-29 20:50 UTC, momo5502 commented on src/client/component/dvar_cheats.cpp
> +		a.call(set_client_dvar_by_string);
did you make sure that the stack is properly aligned (0x10) for the call? otherwise sse instructions will fail

2020-11-29 20:50 UTC, momo5502 commented on src/client/game/symbols.hpp
> +	WEAK Symbol<void(const char*, const char*, DvarSetSource)> Dvar_SetFromStringByNameFromSource{0x14042D000, 0x1404F00B0};
space between void and bracket

2020-11-29 20:50 UTC, momo5502 commented on src/client/game/symbols.hpp
> +	WEAK Symbol<void(int localClientNum, mp::cg_s* cg, const char* dvar, const char* value)> CG_SetClientDvarFromServer{0x0, 0x14028A2C0 };
space between void and bracket

2020-11-29 20:50 UTC, momo5502 commented on src/client/component/dvar_cheats.cpp
> +		const auto* dvar = game::Scr_GetString(0); // grab the original dvar again since it's never stored on stack
Not sure if people are aware of this, but the Scr_GetWhatever functions can cause unwinding using longjmp.
It is therefore potentially unsafe. The script_value class is a safe abstraction for VM objects. However, there is no portably way to access values from the script stack, yet, so calling Scr_GetString is fine for now, but I simply want people to be aware of that.

2020-11-29 20:52 UTC, momo5502 commented on src/client/component/dvar_cheats.cpp
> +		a.call(set_client_dvar_by_string);
also the caller needs to reserve stack space for the calle, this is done using pushad64, it automatically does that, unless you push additional values to the stack, but i think you didn't. However stack alignment for further calls is not handled by it.

2020-11-29 21:45 UTC, skiff commented on src/client/component/dvar_cheats.cpp
> +		a.call(set_client_dvar_by_string);
Honestly I'm not entirely sure what you mean by this, or at least what needs to be changed so that this is correct

2020-11-29 21:46 UTC, skiff commented on src/client/component/dvar_cheats.cpp
> +		const auto* dvar = game::Scr_GetString(0); // grab the original dvar again since it's never stored on stack
It could cause problems, but with this only being called by the PlayerCmd_ function where Scr_GetString(0) was already called successfully I didn't think it would be an issue. Only other way at the moment I could think of to do this properly was to reverse the entire SetClientDvar function

2020-11-29 22:01 UTC, momo5502 commented on src/client/component/dvar_cheats.cpp
> +		a.call(set_client_dvar_by_string);
I'll checkout your PR tomorrow and verify if everything is alright

2020-11-30 21:05 UTC, RektInator commented
I would personally vote against this, you don't need to change client settings in order to make a mod.

2020-11-30 21:42 UTC, momo5502 commented
> I would personally vote against this, you don't need to change client settings in order to make a mod.

Certain dvars that need to be changed by mods are client dvars. Anything that is rendered or computed on client side needs to be changed that way. Eg. pyhsics values (speed, jump height, ...). The question is if we block setting saved dvars? But I mean you can always make your config write protected. I always had that and it worked perfectly

2020-11-30 21:42 UTC, momo5502 approved these changes

2020-11-30 21:42 UTC, merged

2020-11-30 22:03 UTC, RektInator commented
> > I would personally vote against this, you don't need to change client settings in order to make a mod.
> 
> Certain dvars that need to be changed by mods are client dvars. Anything that is rendered or computed on client side needs to be changed that way. Eg. pyhsics values (speed, jump height, ...). The question is if we block setting saved dvars? But I mean you can always make your config write protected. I always had that and it worked perfectly

No, dvars like speed / jump / height are applied on the server side. They are then transferred over to the client and set there as well (based on the flags of the dvar, the replicated flag). This uses the configstrings mechanism. Replicated flags can also be changed while the client is already connected to the server.

If a server config dvar should also be changed on the client (anything related to movement for example), it should get the replicated flag instead.

2020-11-30 22:21 UTC, momo5502 commented
> > > I would personally vote against this, you don't need to change client settings in order to make a mod.
> > 
> > 
> > Certain dvars that need to be changed by mods are client dvars. Anything that is rendered or computed on client side needs to be changed that way. Eg. pyhsics values (speed, jump height, ...). The question is if we block setting saved dvars? But I mean you can always make your config write protected. I always had that and it worked perfectly
> 
> No, dvars like speed / jump / height are applied on the server side. They are then transferred over to the client and set there as well (based on the flags of the dvar, the replicated flag). This uses the configstrings mechanism. Replicated flags can also be changed while the client is already connected to the server.
> 
> If a server config dvar should also be changed on the client (anything related to movement for example), it should get the replicated flag instead.

This is true for global configurations, but if you want to apply certain changes to individual players, e.g. you are making a mod and want one player to be some fucking easter bunny or so and want him to be able to jump like a retard, then you need such a mechansim, as a replicated dvar is replicated to all clients, and not just to a single one. (As an example, there might be better examples for this, again, my idea is to maybe block saved dvars!)

2020-11-30 22:24 UTC, RektInator commented
> > > > I would personally vote against this, you don't need to change client settings in order to make a mod.
> > > 
> > > 
> > > Certain dvars that need to be changed by mods are client dvars. Anything that is rendered or computed on client side needs to be changed that way. Eg. pyhsics values (speed, jump height, ...). The question is if we block setting saved dvars? But I mean you can always make your config write protected. I always had that and it worked perfectly
> > 
> > 
> > No, dvars like speed / jump / height are applied on the server side. They are then transferred over to the client and set there as well (based on the flags of the dvar, the replicated flag). This uses the configstrings mechanism. Replicated flags can also be changed while the client is already connected to the server.
> > If a server config dvar should also be changed on the client (anything related to movement for example), it should get the replicated flag instead.
> 
> This is true for global configurations, but if you want to apply certain changes to individual players, e.g. you are making a mod and want one player to be some fucking easter bunny or so and want him to be able to jump like a retard, then you need such a mechansim, as a replicated dvar is replicated to all clients, and not just to a single one. (As an example, there might be better examples for this, again, my idea is to maybe block saved dvars!)

Fair point, not sure if these kind of dvars can be different from the server though, I think the server also calculates player movement for example based on the dvars saved on the server, at least it does for some other movement stuff.

2020-11-30 22:25 UTC, momo5502 commented
> > > > > I would personally vote against this, you don't need to change client settings in order to make a mod.
> > > > 
> > > > 
> > > > Certain dvars that need to be changed by mods are client dvars. Anything that is rendered or computed on client side needs to be changed that way. Eg. pyhsics values (speed, jump height, ...). The question is if we block setting saved dvars? But I mean you can always make your config write protected. I always had that and it worked perfectly
> > > 
> > > 
> > > No, dvars like speed / jump / height are applied on the server side. They are then transferred over to the client and set there as well (based on the flags of the dvar, the replicated flag). This uses the configstrings mechanism. Replicated flags can also be changed while the client is already connected to the server.
> > > If a server config dvar should also be changed on the client (anything related to movement for example), it should get the replicated flag instead.
> > 
> > 
> > This is true for global configurations, but if you want to apply certain changes to individual players, e.g. you are making a mod and want one player to be some fucking easter bunny or so and want him to be able to jump like a retard, then you need such a mechansim, as a replicated dvar is replicated to all clients, and not just to a single one. (As an example, there might be better examples for this, again, my idea is to maybe block saved dvars!)
> 
> Fair point, not sure if these kind of dvars can be different from the server though, I think the server also calculates player movement for example based on the dvars saved on the server, at least it does for some other movement stuff.

Yeye, that's why I said this might be a bad example, but you get my point. There might be other applications for this feature.

2020-11-30 22:26 UTC, RektInator commented
> > > > > > I would personally vote against this, you don't need to change client settings in order to make a mod.
> > > > > 
> > > > > 
> > > > > Certain dvars that need to be changed by mods are client dvars. Anything that is rendered or computed on client side needs to be changed that way. Eg. pyhsics values (speed, jump height, ...). The question is if we block setting saved dvars? But I mean you can always make your config write protected. I always had that and it worked perfectly
> > > > 
> > > > 
> > > > No, dvars like speed / jump / height are applied on the server side. They are then transferred over to the client and set there as well (based on the flags of the dvar, the replicated flag). This uses the configstrings mechanism. Replicated flags can also be changed while the client is already connected to the server.
> > > > If a server config dvar should also be changed on the client (anything related to movement for example), it should get the replicated flag instead.
> > > 
> > > 
> > > This is true for global configurations, but if you want to apply certain changes to individual players, e.g. you are making a mod and want one player to be some fucking easter bunny or so and want him to be able to jump like a retard, then you need such a mechansim, as a replicated dvar is replicated to all clients, and not just to a single one. (As an example, there might be better examples for this, again, my idea is to maybe block saved dvars!)
> > 
> > 
> > Fair point, not sure if these kind of dvars can be different from the server though, I think the server also calculates player movement for example based on the dvars saved on the server, at least it does for some other movement stuff.
> 
> Yeye, that's why I said this might be a bad example, but you get my point. There might be other applications for this feature.

Alright sounds good bro