Add chat notifies
XLabsProject/iw6x-client pull request #235
Opened 2020-12-08 02:11 UTC by fedddddd

2020-12-08 07:19 UTC, momo5502 requested changes
The say command has already been registered in party.cpp
I suggest hooking the server command handler instead.
Also not sure if you are calling script api functions from the right thread.

2020-12-09 07:54 UTC, momo5502 requested changes
That's not what I meant by hooking the handler.
Just check how it was done in IW4x: https://github.com/XLabsProject/iw4x-client/blob/a2a303c3d0500c1f0bde8250ae375fd747e8b6e4/src/Components/Modules/Dedicated.cpp#L308

2020-12-09 22:16 UTC, momo5502 requested changes
A few small things to change, otherwise this pull request starts looking very good 👍

2020-12-09 22:16 UTC, momo5502 commented on src/client/component/logfile.cpp
> +		a.call(0x1404F63C0);
Use call_aligned instead here.
The reason is the stack needs to be 0x10 aligned before a call and you have to reserve a stack frame for the callee. The call_aligned macro does that automatically for you.

2020-12-09 22:16 UTC, momo5502 commented on src/client/component/logfile.cpp
> +		a.call(evaluate_say);
Same here

2020-12-09 22:16 UTC, momo5502 commented on src/client/component/logfile.cpp
> +			const auto level = scripting::entity(*game::levelEntityId);
Scripting interaction strictly requires this code to be executed on the server thread. Is this the case? Did you verify it? You can do so by debugging the code and setting a breakpoint here. Then, in Visual Studio, check the name of the thread this function was called, it should be called "Server".

2020-12-09 22:40 UTC, fedddddd commented on src/client/component/logfile.cpp
> +			const auto level = scripting::entity(*game::levelEntityId);
Yes it is the server thread

2020-12-09 22:40 UTC, fedddddd commented on src/client/component/logfile.cpp
> +		a.call(0x1404F63C0);
Good to know thanks

2020-12-11 14:59 UTC, momo5502 approved these changes

2020-12-11 15:00 UTC, merged