Bouncing from all angles
XLabsProject/iw6x-client pull request #546
Opened 2022-02-01 18:19 UTC by diamante0018

- bg_bouncingAllAngles, this forces the game to make the player bounce more easily (won't work unless the other dvar is set to true)
- pm_bouncing renamed to bg_bouncing as the pm_prefix is non-standard. bg = both games, dvars are replicated so it is a more fitting prefix.

- Well tested

2022-02-01 22:40 UTC, Jemal commented
The dvar prefix should remain as pm_ since its related to player movement. All the code related to this is prefixed with PM_ (Player Movement).

2022-02-02 08:54 UTC, diamante0018 commented
> The dvar prefix should remain as pm_ since its related to player movement. All the code related to this is prefixed with PM_ (Player Movement).

I dislike going against the game's naming conventions but I guess this one can't hurt anyone 😄 
I renamed the dvars back to pm_

2022-02-03 21:09 UTC, Jemal requested changes

2022-02-03 21:09 UTC, Jemal commented on src/client/component/gameplay.cpp
> +		void pm_project_velocity_stub(const float* velIn, const float* normal, float* velOut)
snake case the parameters

2022-02-03 21:23 UTC, diamante0018 commented on src/client/component/gameplay.cpp
> +		void pm_project_velocity_stub(const float* velIn, const float* normal, float* velOut)
Done

2022-02-06 10:43 UTC, momo5502 approved these changes

2022-02-06 10:43 UTC, merged