Add raw mouse component, fixes #117
XLabsProject/iw6x-client pull request #604
Opened 2022-04-30 03:51 UTC by GEEKiDoS

2022-04-30 08:25 UTC, diamante0018 commented on src/client/component/raw_mouse.cpp
> +			const auto *r_displayMode = game::Dvar_FindVar("r_displayMode");
Could you move the pointer to the left please?

2022-04-30 08:25 UTC, diamante0018 commented on src/client/game/structs.hpp
> +	struct __declspec(align(8)) WinVars_t
Static asserts (the size of struct) are appreciated. Could also confirm whenever the declspec align directive is really needed

2022-05-03 08:37 UTC, diamante0018 requested changes

2022-05-03 08:37 UTC, diamante0018 commented on src/client/component/raw_mouse.cpp
> +			const auto* r_displayMode = game::Dvar_FindVar("r_displayMode");
Wouldn't this make it lookup the dvar every time the function is called?
Aren't you looking for 'static' just like I think you used in the patch you wrote for IW4x?

2022-05-03 08:37 UTC, diamante0018 commented on src/client/component/raw_mouse.cpp
> +				static tagPOINT current_position;
Does this need to be static?

2022-05-03 08:37 UTC, diamante0018 commented on src/client/component/raw_mouse.cpp
> +				static BYTE lpb[sizeof(RAWINPUT)];
Does this need to be static?

2022-05-03 10:31 UTC, GEEKiDoS commented on src/client/component/raw_mouse.cpp
> +			const auto* r_displayMode = game::Dvar_FindVar("r_displayMode");
Any other Dvar_FindVar calls in this project didn't using the static keyword for returning value so I removed that

2022-05-03 10:33 UTC, GEEKiDoS commented on src/client/component/raw_mouse.cpp
> +				static BYTE lpb[sizeof(RAWINPUT)];
Well I actually just copied code from the microsoft document https://docs.microsoft.com/en-us/windows/win32/dxtecharts/taking-advantage-of-high-dpi-mouse-movement#code-try-2

2022-05-03 10:38 UTC, diamante0018 commented on src/client/component/raw_mouse.cpp
> +			const auto* r_displayMode = game::Dvar_FindVar("r_displayMode");
Perhaps in other parts of the project, the calls to Dvar_FindVar are not done each time such a repetitive action is performed (like a mouse move)? Am I missing something? If you want you can add this dvar to the dvar file in the game's folder so it can also be accessed globally and will only be fetched once.

2022-05-03 10:44 UTC, mjkzy commented on src/client/game/symbols.hpp
> +	WEAK symbol<BOOL(HWND hWnd, UINT uMsg, WPARAM wParam, LPARAM lParam)>MainWndProc{0x14043E6A0, 0x140504A00};
put spacing between name and symbol thing 
(ex: `LPARAM lParam)>MainWndProc` > `LPARAM lParam)> MainWndProc`

2022-05-08 23:48 UTC, diamante0018 commented
Fixes #117

2022-06-27 18:44 UTC, diamante0018 commented
Hi @GEEKiDoS, can you address the comments?
I would move the r_displayMode code to the anonymous namespace as a game::dvar_t** aka find where the pointer is stored in memory so it can be fetched easily and fast.
I've done this on iw4x multiple times. so it would look like
`game::dvar_t**  r_displayMode = reinterpret_cast<game::dvar_t**>(address);`
thanks

2022-07-31 19:42 UTC, diamante0018 approved these changes

2022-07-31 19:52 UTC, merged