Fix sending packets longer than 1288 bytes
XLabsProject/iw6x-client pull request #608
Opened 2022-05-08 14:42 UTC by skiff

fixes #204 / #606. redirects Sys_SendPacket to go straight to raw socket without trying to copy data to limited buffer first

2022-05-08 14:57 UTC, diamante0018 requested changes

2022-05-08 14:57 UTC, diamante0018 commented on src/client/game/symbols.hpp
> +	WEAK symbol<void(netadr_s*, sockaddr*)> NetadrToSockadr{ 0, 0x1404E53D0 };
Remove spaces between { and the addresses please

2022-05-08 14:57 UTC, diamante0018 commented on src/client/component/network.cpp
> +	int dw_send_to_stub(const int size, const char* src, game::netadr_s* a3)
Couldn't you label the third argument? I'm sure it's easy to find the original name

2022-05-08 15:16 UTC, diamante0018 approved these changes

2022-05-09 06:50 UTC, momo5502 approved these changes

2022-05-09 06:50 UTC, merged